### PR TITLE
Adding Warn module

### PR DESCRIPTION
**Pull request by MrRedSheep**
Adding Warn module,
Tested 
Added /warn and /warnp command

### CODE REVIEW

**Comment by psrcek** [comment]
Closing this for the following reasons:
- Why the hell is the module in javautils/warn/warn/warn.java
- Why the hell is the class name not capitalized
- Why the hell is there an empty onEnable function
- What the hell are those commit messages

**Comment by jomo** [comment]
@psrcek you can [request changes](https://help.github.com/articles/about-pull-request-reviews/) instead of closing PRs.
PS: removed some 'why the hell's from your comment 😎

**Comment by Dico200** [comment]
@MrRedSheep I suggest you join me in writing a module for this to teach you some more java basics :)
I'll add blockplacemods not too long from now.

**Comment by MrRedSheep** [comment]
@Dico200 already made another pull request(accepted), but I’d like to see how I could make my code working :)

**Comment by Dico200** [comment]
When do you have time? :)

**Pull request closed without merging**
